# Generated by Django 3.2 on 2021-04-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_status', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Undefined', 'U'), ('Male', 'M'), ('Female', 'F')], default='U', max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=100)),
                ('lgn', models.CharField(max_length=100)),
            ],
        ),
    ]
