# Generated by Django 3.2 on 2021-04-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
